name: apply

on:
    push:
    branches: [ "master" ]
    pull_request:
    branches: [ "master" ]
  # workflow_dispatch:
  #    inputs : 
  #     region :
  #       description: "Enter your data : "
  #       required: true  
  #       type: string 

jobs:
  newrelic_dash:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform hashicorp setup
        uses: hashicorp/setup-terraform@v2
          
      - name: terraform init
        run: |
          cd module
          terraform init 
      - name: terraform plan
        run: |
          cd module
          terraform plan
      - name: terraform apply
        run: |
          cd module 
          terraform apply -auto-approve